# Generated by Django 3.1.6 on 2021-05-12 22:10

import crops.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0033_auto_20210503_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=crops.models.upload_location)),
                ('crop_description', tinymce.models.HTMLField(blank=True)),
                ('varieties', tinymce.models.HTMLField(blank=True)),
                ('processing_type', tinymce.models.HTMLField(blank=True)),
                ('quality_factor', tinymce.models.HTMLField(blank=True)),
                ('price_factor', tinymce.models.HTMLField(blank=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date-published')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
