# Generated by Django 3.1.6 on 2021-05-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crops',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
