# Generated by Django 3.1.6 on 2021-05-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_crops_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='category',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
