# Generated by Django 3.1.6 on 2021-05-23 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_auto_20210515_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crops',
            options={'ordering': ('-publish',), 'verbose_name': 'crop', 'verbose_name_plural': 'crops'},
        ),
    ]
