# Generated by Django 3.1.6 on 2021-04-25 18:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('region', models.CharField(choices=[('Arusha', 'Arusha'), ('Dar es Salaam', 'Dar es Salaam'), ('Geita', 'Geita'), ('Kagera', 'Kagera'), ('Mwanza', 'Mwanza'), ('Morogoro', 'Morogoro'), ('Shinyanga', 'Shinyanga'), ('Tabora', 'Tabora'), ('Singida', 'Singida'), ('Simiyu', 'Simiyu'), ('Mbeya', 'Mbeya')], max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=50)),
                ('product_name', models.CharField(choices=[('Maize', 'Maize'), ('Rice', 'Rice'), ('Beans', 'Beans'), ('Carrot', 'Carrot'), ('Cabage', 'Cabage'), ('Beans', 'Beans')], max_length=100)),
                ('scale', models.CharField(choices=[('KG', 'Kg'), ('DEBE', 'Debe'), ('GUNIA', 'Gunia'), ('TANI', 'Tani')], default='Kg', max_length=50)),
                ('price', models.FloatField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='static/img/')),
            ],
        ),
    ]
