# Generated by Django 3.1.6 on 2021-04-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postproduct',
            name='amount',
            field=models.CharField(default='', max_length=50),
        ),
    ]
