# Generated by Django 3.1.6 on 2021-04-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_postproduct_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproduct',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
