# Generated by Django 3.1.6 on 2021-04-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20210425_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postproduct',
            name='district',
        ),
        migrations.RemoveField(
            model_name='postproduct',
            name='ward',
        ),
        migrations.AddField(
            model_name='postproduct',
            name='location',
            field=models.CharField(default='', max_length=150),
        ),
    ]
