# Generated by Django 3.1.6 on 2021-04-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_auto_20210425_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproduct',
            name='amount',
            field=models.IntegerField(default='00'),
        ),
    ]
