# Generated by Django 3.1.6 on 2021-05-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_postproduct_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postproduct',
            name='category',
        ),
    ]
