# Generated by Django 3.1.6 on 2021-05-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_auto_20210514_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postproduct',
            old_name='location',
            new_name='district',
        ),
        migrations.AddField(
            model_name='postproduct',
            name='ward',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='postproduct',
            name='product_name',
            field=models.CharField(choices=[('Maize', 'Maize'), ('Rice', 'Rice'), ('Beans', 'Beans'), ('Carrot', 'Carrot'), ('Cabage', 'Cabage'), ('Beans', 'Beans'), ('Vegetables', 'Vegetables'), ('Ginger', 'Ginger'), ('Garlic', 'Garlic'), ('Banana', 'Banana'), ('Tomato', 'Tomato'), ('Lemon', 'Lemon'), ('Coffee', 'Coffee')], max_length=100),
        ),
    ]
