# Generated by Django 3.1.6 on 2021-05-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0014_auto_20210515_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproduct',
            name='phone_number',
            field=models.IntegerField(max_length=13),
        ),
    ]
