# Generated by Django 3.1.6 on 2021-05-28 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0026_remove_order_customer'),
        ('accounts', '0002_auto_20210529_0133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
