# Generated by Django 3.1.6 on 2021-02-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(default=True, upload_to=''),
            preserve_default=False,
        ),
    ]
