# Generated by Django 3.1.6 on 2021-03-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210307_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='overview',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
