# Generated by Django 3.1.6 on 2021-03-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='overview',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
