# Generated by Django 3.1.6 on 2021-03-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210307_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='overview',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
