# Generated by Django 3.1.6 on 2021-03-10 21:56

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_auto_20210307_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overview', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150, null=True, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location)),
                ('content', tinymce.models.HTMLField()),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date-published')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('news_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('featured_news', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish_date',),
            },
        ),
    ]
