# Generated by Django 3.1.6 on 2021-03-13 13:25

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='featured_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='blog.author'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to='blog.author'),
        ),
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.img_location),
        ),
    ]
