# Generated by Django 3.1.6 on 2021-03-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210313_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='overview',
            field=models.CharField(max_length=145),
        ),
    ]
