# Generated by Django 3.1.6 on 2021-03-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210313_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='overview',
            field=models.CharField(max_length=140),
        ),
    ]
