# Generated by Django 3.1.6 on 2021-03-21 22:58

import blog.models
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210320_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
