# Generated by Django 3.1.6 on 2021-03-21 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_practiceintro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceintro',
            name='image',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
