# Generated by Django 3.1.6 on 2021-03-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210322_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceintro',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
