# Generated by Django 3.1.6 on 2021-03-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_practiceintro_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceintro',
            name='overview',
            field=models.CharField(default='', max_length=305),
        ),
    ]
