# Generated by Django 3.1.6 on 2021-03-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20210330_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='category',
            new_name='categories',
        ),
    ]
