# Generated by Django 3.1.6 on 2021-03-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20210330_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-publish_date',), 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
