# Generated by Django 3.1.6 on 2021-04-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20210331_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='overview',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
