# Generated by Django 3.1.6 on 2021-04-11 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20210409_1303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
