# Generated by Django 3.1.6 on 2021-05-03 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
