# Generated by Django 3.1.6 on 2021-05-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_newscomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscomment',
            old_name='post',
            new_name='news',
        ),
    ]
