# Generated by Django 3.1.6 on 2021-05-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('Arusha', 'Arusha'), ('Dar es Salaam', 'Dar es Salaam'), ('Geita', 'Geita'), ('Kagera', 'Kagera'), ('Mwanza', 'Mwanza'), ('Morogoro', 'Morogoro'), ('Shinyanga', 'Shinyanga'), ('Tabora', 'Tabora'), ('Singida', 'Singida'), ('Simiyu', 'Simiyu'), ('Mbeya', 'Mbeya'), ('Mara', 'Mara'), ('Kilimanjaro', 'Kilimanjaro'), ('Tanga', 'Tanga'), ('Kigoma', 'Kigoma'), ('Mtwara', 'Mtwara'), ('Pwani', 'Pwani'), ('Simiyu', 'Simiyu'), ('Songwe', 'Songwe'), ('Lindi', 'Lindi'), ('Dodoma', 'Dodoma'), ('Singida', 'Singida'), ('Ruvuma', 'Ruvuma'), ('Njombe', 'Njombe')], max_length=150),
        ),
    ]
