# Generated by Django 3.1.6 on 2021-04-15 10:12

from django.db import migrations, models
import django.utils.timezone
import products.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=products.models.upload_location)),
                ('varieties', tinymce.models.HTMLField()),
                ('processing_type', tinymce.models.HTMLField()),
                ('quality_factor', tinymce.models.HTMLField()),
                ('priec_factor', tinymce.models.HTMLField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date-published')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('categories', models.ManyToManyField(to='products.Category')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
