# Generated by Django 3.1.6 on 2021-04-18 20:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='priec_factor',
        ),
        migrations.AddField(
            model_name='product',
            name='price_factor',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='processing_type',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quality_factor',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='varieties',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
