# Generated by Django 3.1.6 on 2021-04-18 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_delete_faq'),
        ('products', '0003_auto_20210418_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.author'),
        ),
    ]
