# Generated by Django 3.1.6 on 2021-05-03 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
